// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwoNwBTTkURs6-VbK4M-YPoN4u95XohS4',
    appId: '1:1027084087987:web:08b006d45d93236ccf36c6',
    messagingSenderId: '1027084087987',
    projectId: 'e-com2024-77429',
    authDomain: 'e-com2024-77429.firebaseapp.com',
    storageBucket: 'e-com2024-77429.firebasestorage.app',
    measurementId: 'G-ZKSPD5MEC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuhKJBEvZRWbJGn4pNAoMQx5HjwfxkegE',
    appId: '1:1027084087987:android:f8cc80ae073ef348cf36c6',
    messagingSenderId: '1027084087987',
    projectId: 'e-com2024-77429',
    storageBucket: 'e-com2024-77429.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq2YjZepIXmLfZhVxTacRc3BtsgaJatlc',
    appId: '1:1027084087987:ios:19336b7db9be75a4cf36c6',
    messagingSenderId: '1027084087987',
    projectId: 'e-com2024-77429',
    storageBucket: 'e-com2024-77429.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp2024',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwoNwBTTkURs6-VbK4M-YPoN4u95XohS4',
    appId: '1:1027084087987:web:cad087912e8faf62cf36c6',
    messagingSenderId: '1027084087987',
    projectId: 'e-com2024-77429',
    authDomain: 'e-com2024-77429.firebaseapp.com',
    storageBucket: 'e-com2024-77429.firebasestorage.app',
    measurementId: 'G-C8ZLMQ22CB',
  );
}
